### ISSUE TITLE
Homepage url is incorrect (//)

### ISSUE THREAD

**Issue by thangngoc89** [MoOx/statinamic#104]
This is from my exeperinces, might be good for docs:

- ~~On collection page #100~~
- When generate page with date and time. (due to timezone differences)

 ref https://github.com/thangngoc89/blog/commit/a3f28a946f42e229fb7a280a7c9d5d24e45477ad

- Nav link with active state (this could be added to docs site code for desmontration)
https://github.com/thangngoc89/blog/blob/master/web_modules/components/Sidebar/Sidebar.js#L19-L22

**Comment by MoOx** [comment]
The first point (collection diff) will be handled in #96.

For the date, I think this will be added to faq

For the active state, it seems like it's a bug from the static build?

**Comment by thangngoc89** [comment]
Nope. For active state, see this https://github.com/MoOx/statinamic/pull/107/files#diff-57e8ba7d57e5f6152bb41b42683cb98dR53

**Comment by MoOx** [comment]
Having "/statinamic//" looks like a bug to me.

**Comment by thangngoc89** [comment]
Ok then. let's find that bug

**Comment by MoOx** [comment]
(Maybe introduced with react-router 2)

**Comment by thangngoc89** [comment]
I don't think so. I hack #107 when react-router 1

**Comment by MoOx** [comment]
So I guess this is good now, #96.

**Comment by thangngoc89** [comment]
The third one is still there.(index link is // )

**Comment by MoOx** [comment]
Can you provide me any pointer of where you get this url?

**Comment by thangngoc89** [comment]
https://github.com/thangngoc89/blog/blob/c6ba46c941a5a94c07b9667fc5d95db925780bd0/web_modules/Sidebar/Sidebar.js#L20

https://github.com/thangngoc89/blog/blob/c6ba46c941a5a94c07b9667fc5d95db925780bd0/web_modules/LayoutContainer/LayoutContainer.js#L43

https://github.com/MoOx/statinamic/blob/master/src/static/to-html/url-as-html.js#L40

**Comment by MoOx** [comment]
I guess something like this will do the trick `location: "/" + url ? url + "/" : ""` ?

**Comment by thangngoc89** [comment]
Nope. In docs,  url will always prefix with statinamic so this doesn't help.

So ref #115

**Comment by MoOx** [comment]
The module filename-to-url is supposed to clean url from surrounding slashes. Maybe we should use it somewhere it's not to remove those.

**Comment by MoOx** [comment]
https://github.com/MoOx/statinamic/blob/8d79ef1490fe0cd19e3b7130df51aac9da467078/src/filename-to-url/__tests__/index.js#L71-L77

**Comment by thangngoc89** [comment]
:+1: we should have a consistence url type across the app. Sometimes,  we have trailing slashes, sometimes not,  ...

**Comment by MoOx** [comment]
That's why I create this tiny module. It's used in a lot of place already.
Btw, I think this should do the trick `location: "/" + url ? filenameToUrl(url) + "/" : ""`.
And I think I am going to rename this module to "normalize-url".

**Comment by halvves** [comment]
I'm not sure if this should be discussed in a different issue or not, but to avoid noise, I'm starting with keeping it in here.

the og:url is also incorrect as a result of this.
https://github.com/MoOx/statinamic/blob/master/boilerplate/web_modules/layouts/Page/index.js#L46

i'm also thinking the the boiler plate og:url should be: `{ property: "og:url", content: pkg.homepage + __url }` as og:url should be the full path to the page.

Also. I don't know if this is any help, but it seems that this is where the `//` gets created. On local dev it sets `__url` to `\/`.

**Comment by MoOx** [comment]
Thanks. I am currently review how url are generated (and then consumed) for #47. I will double check to close this issue as well.

**Comment by MoOx** [comment]
@thangngoc89 following this comment: https://github.com/MoOx/statinamic/issues/104#issuecomment-184097031
reac-router provide "splat" param without trailing slash, so for urls like "/blah/blah/", react-router provide "/blah/blah", that why I started to remove trailing slash. And then somethimes your get base url like http://domain.ext/ where you concat an uri and might got http://domain.ext//blah/blah/, that why I removed leading slash.
So for now we (will) have most url with slashes everywhere except in the store. I will see if I can handle that now that I changed most place where url are used.

**Comment by thangngoc89** [comment]
:+1:

**Comment by thangngoc89** [comment]
Fixed in 0.8.0.

**Comment by MoOx** [comment]
Closed by  865622e
