### ISSUE TITLE
Doc autodeploy broken

### ISSUE THREAD

**Issue by MoOx** [MoOx/statinamic#116]
https://travis-ci.org/MoOx/statinamic/jobs/108143031

**Comment by MoOx** [comment]
Fixed, btw I switched to the gh-pages package. Will udpate doc to recommend this one.

**Comment by thangngoc89** [comment]
Please change your gh pages token immediately. You are exposing your token in travis.

**Comment by MoOx** [comment]
Don't worry, I already deleted it :)
Thanks!
