### ISSUE TITLE
Less verbose log in dev mode

### ISSUE THREAD

**Issue by thangngoc89** [MoOx/statinamic#118]
This is how my console looks like when starting startinamic on postcss.org

![screenshot from 2016-02-10 23 04 15](https://cloud.githubusercontent.com/assets/3049054/12952913/e575adb8-d04a-11e5-8b6d-d3ed9f921137.png)

Maybe replace coonsole.log and nanoLog with [debug](https://www.npmjs.com/package/debug) ?

**Comment by MoOx** [comment]
Why not :)

**Comment by thangngoc89** [comment]
:+1:
