### ISSUE TITLE
Can't create CNAME and .nojekyll file

### ISSUE THREAD

**Issue by thangngoc89** [MoOx/statinamic#120]
Currently, there is no way to overwrite in configurator. (CNAME, .nojekyll)

Just look at this line https://github.com/MoOx/statinamic/blob/master/src/configurator/index.js#L9

**Comment by MoOx** [comment]
You sure? https://github.com/MoOx/statinamic/blob/master/src/configurator/index.js#L23

**Comment by MoOx** [comment]
Btw I am not even sure the pkg you mentionned is useful

**Comment by thangngoc89** [comment]
Sorry. My fault. But I'm sure that I can't get postbuild to produce CNAME and .nojekyll file. I'll take another look

**Comment by MoOx** [comment]
Did you respect this format http://moox.io/statinamic/docs/usage/configuration/ ? (in pkg.statinamic section)

**Comment by thangngoc89** [comment]
Yup https://github.com/thangngoc89/postcss.org/blob/statinamic-0.7/package.json#L17-L18

**Comment by thangngoc89** [comment]
These LoC is the problem

https://github.com/MoOx/statinamic/blob/master/src/configurator/index.js#L32-L56


```
console.log(
    minimist(argv, {
      alias: {
        "dev-host": "devHost",
        "dev-port": "devPort",
      },

      // TODO validate string and flags after, so values from pkg.json are
      // validated too
      string: [
        "cwd",
        "source",
        "destination",
        "assets",
        "devHost",
        "devPort",
      ],
      boolean: [
        "CNAME",
        "nojekyll",
        "dev",
        "production",
        "static",
        "server",
      ],
    }),
  )
```

```
{ _: [ 'node', '/home/khoa/web/postcss.org/scripts/build' ],
  CNAME: false,
  nojekyll: false,
  dev: false,
  production: true,
  static: true,
  server: false }
```

**Comment by MoOx** [comment]
We should fix and test this https://github.com/MoOx/statinamic/blob/master/src/configurator/__tests__/index.js

**Comment by MoOx** [comment]
How do you think we should merge pkg + cli args?
Maybe we should merge previous config with argv before passing to minimist?

**Comment by thangngoc89** [comment]
I don't have much experience about this

**Comment by MoOx** [comment]
I am on it. The scenario:

- load user config
- load user CLI config
- valid all this with error messages
- merge default config, user config, cli only default config, and user CLI config

**Comment by thangngoc89** [comment]
Thanks. :+1:

----
*Nguyen Dang Khoa*

Email : hi@khoanguyen.me
Mobile phone : +841662984348
University of Medicine and Pharmacy, Ho Chi Minh City, Vietnam
Faculty of Odonto-Stomatology, Course 2013 - 2019

2016-02-11 15:26 GMT+07:00 Maxime Thirouin <notifications@github.com>:
