### ISSUE TITLE
Missing NODE_ENV in build script

### ISSUE THREAD

**Issue by thangngoc89** [MoOx/statinamic#133]
`process.env.NODE_ENV` is defined on client side only (ref https://github.com/MoOx/statinamic/blob/51023e293d674ad49d30e39b9925769389f575cc/docs/scripts/webpack.config.babel.js#L92-L94)

On static build, `process.env.NODE_ENV === undefined` . So we need to set NODE_ENV in build script

**Comment by MoOx** [comment]
Good catch.

**Comment by MoOx** [comment]
Fixed on "next" branch. I did not release immediately as a patch since stylelint 4.3.0 is "broken" (https://github.com/stylelint/stylelint/pull/737)

**Comment by thangngoc89** [comment]
Stylelint 4.3.2 is out.
