### ISSUE TITLE
Bug in dev server when working with webpack hmr

### ISSUE THREAD

**Issue by thangngoc89** [MoOx/statinamic#136]
It is hard to explain this issue. Perhap some log : 

First, log assetsFiles in [url-to-html](https://github.com/MoOx/statinamic/blob/ef975cfd199f6cee50203bdc712b8037325c90d9/src%2Fstatic%2Fto-html%2Furl-as-html.js)

- First build: 

`js: [ [ 'statinamic-client.abc14b6e4bf565b15933.js' ] ]`

- Trigger a HMR (edit any component), refresh browser/open new tab

```
 js: 
   [ [ 'statinamic-client.abc14b6e4bf565b15933.js' ],
     [ 'statinamic-client.90ca3ce7e1bc5ee67839.js',
       '0.abc14b6e4bf565b15933.hot-update.js' ] ],
```

Error in console:

`http://0.0.0.0:3000/statinamic/statinamic-client.90ca3ce7e1bc5ee67839.js,0.abc14b6e4bf565b15933.hot-update.js` doesn't not exits

`assetsFiles.js` suppose to take an array of string, not an array of array. so the above error is the result of

```
[ 'statinamic-client.90ca3ce7e1bc5ee67839.js', '0.abc14b6e4bf565b15933.hot-update.js' ].toString()
```

---
Edit: 

This should be an easy fix, just include latest `statinamic-client` file and we are good to go.

But the problem is when we do that, React will complain about invalid checksum. since dev server doesn't get the latest layout.

**Comment by MoOx** [comment]
Will fix that.
And maybe we should not use hash during dev.

**Comment by MoOx** [comment]
Fixed in "next" branch.

**Comment by thangngoc89** [comment]
You are fixing it in the wrong way. Anyway,  the problem is not with hashing,  it is because of HMR. After this was fixed,  user will receive false alert about invalid checksum. (Since only the client got update, server doesn't)

**Comment by thangngoc89** [comment]
let's continue discussion here #140
