### ISSUE TITLE
Switch to remark (formerly mdast)

### ISSUE THREAD

**Issue by thangngoc89** [MoOx/statinamic#149]
I found out that remark have a plugin called [remark-react](https://github.com/mapbox/remark-react/blob/master/readme.md) to render markdown into react component.

This will help us with internal link issue.

For code hightlight,  there is a long debate [here](https://github.com/mapbox/remark-react/issues/14).  remark's author made something called [lowlight](https://github.com/wooorm/lowlight/blob/master/readme.md) to handle this.

**Comment by MoOx** [comment]
Is lowlight a remark plugin? It doesn't look like one.

**Comment by thangngoc89** [comment]
Sorry. Lowlight isn't a remark plugin.

@wooorm could you give us some info. Can we use lowlight with remark,  remark-react

**Comment by wooorm** [comment]
Lowlight is not a remark plug-in. [`wooorm/lowlight`](https://github.com/wooorm/lowlight) transforms source code into a syntax tree, which can then be transformed to a virtual DOM for React.

You can use [`conorhastings/react-syntax-highlighter`](https://github.com/conorhastings/react-syntax-highlighter). It’s a react component, using [`wooorm/lowlight`](https://github.com/wooorm/lowlight).

[`mapbox/remark-react`](https://github.com/mapbox/remark-react) doesn’t have support for custom React components yet, so there’s no way to use [`wooorm/lowlight`](https://github.com/wooorm/lowlight) in [`mapbox/remark-react`](https://github.com/mapbox/remark-react). See the issue you yourself linked on what’s happening there.

As you can see, it’s pretty stale. I’m not working on it, neither is @-tmcw. If you want this done you should either do it yourself or convince someone else to work on it :)

**Comment by thangngoc89** [comment]
@-wooorm thank you very much for your information. We'll see what we can do

**Comment by thangngoc89** [comment]
remark-react released 2.0.0 with React 0.14 support 

https://github.com/mapbox/remark-react

**Comment by thangngoc89** [comment]
@MoOx can you take a look here ? 

Using remark will help us remove the catch-links utility. But we had to pull remark, remark-react (and others plugin) to client side. Am I correct ? 

Or we just replace markdown-it with remark for a better AST ?
