### ISSUE TITLE
Redux devtools cause invalid checksum

### ISSUE THREAD

**Issue by thangngoc89** [MoOx/statinamic#152]

**Comment by MoOx** [comment]
It's a know issue. I don't think that's a big deal since it occurs only on development with devtools one (and most people won't even use it).
Maybe we should even remove it from here. People should be able to call redux devtools remotely? (eg: https://github.com/gaearon/redux-devtools#chrome-extension)

**Comment by thangngoc89** [comment]
@MoOx bad DX. Not working with immutablejs

**Comment by MoOx** [comment]
The remote redux devtools?

**Comment by MoOx** [comment]
Ok if we keep it, what do you suggest?

**Comment by thangngoc89** [comment]
I don't have any suggest atm. Can you point me at which line caused this ?

**Comment by MoOx** [comment]
https://github.com/MoOx/statinamic/blob/8d79ef1490fe0cd19e3b7130df51aac9da467078/src/client/index.js#L32

This is only added on client side. Maybe this should be added in static generation.

**Comment by thangngoc89** [comment]
Yup. We can remove persistState() https://github.com/MoOx/statinamic/blob/8d79ef1490fe0cd19e3b7130df51aac9da467078/src/redux/createStore/index.js#L37-L40 to make sure it'll work in node. (if wrap it in `typeof window = 'undefined'` doesn't work)

Maybe flag this at `begining` or `easy first PR` ?

**Comment by MoOx** [comment]
Done :)

**Comment by MoOx** [comment]
You can close issue when a commit lands into master by adding "Closes #XX" in your commit message. No need to close by hand :)
And the nice thing is when someone found the issue (opened) it does make sense since it's not released yet.

https://github.com/blog/1386-closing-issues-via-commit-messages

**Comment by thangngoc89** [comment]
Thank you. Will let github do their job next time.

**Comment by enten** [comment]
@thangngoc89

Awesome fix! Thanks a lot.
