### ISSUE TITLE
allow for custom webpack `info` in config

### ISSUE THREAD

**Issue by VinSpee** [MoOx/statinamic#157]
Hi!

I'd like to be able to set a custom `info` level in the webpack config.

currently, doing

```
devServer: {
  noInfo: true
}
```

doesnt do anything. I'd like to silence webpack's noisy output.

**Comment by thangngoc89** [comment]
So you want `noInfo: false` ?

Just run the server with flag `--verbose`

**Comment by MoOx** [comment]
webpack dev server config is overwritten by hand. I will move this in the boilerplate.

**Comment by VinSpee** [comment]
to clarify @thangngoc89, I'd like noInfo to be true, and I'd rather not have it as a command line flag.

**Comment by thangngoc89** [comment]
@VinSpee there is 2 way to do that (true with other config as well)

- set it in statinamic section / package.json
- modify it in runtime with command line flag.

(read src/configurator and test for more info)

I believe you can speed this up by sending a PR

**Comment by MoOx** [comment]
Closed by 4e286863e09c66d83c09576b5936500055e4c6d9
