### ISSUE TITLE
Create a migration guide

### ISSUE THREAD

**Issue by thangngoc89** [MoOx/statinamic#159]
As public API's changing so fast, it is hard to tell how to upgrade to new version with CHANGELOG (it's a mess imho). I suggest we create a migration guide and update it before every release.

**Comment by MoOx** [comment]
Migration instruction should be in CHANGELOG for now. We are not 1.0 yet so I don't want to take time for migration guide. This is time consuming. And for you information, I don't think we will have a lot of change in the API now.
What we can do is work on the src and docs and after we are happy, we update the boilerplate and offer the diff as a migration guide :D

**Comment by thangngoc89** [comment]
:+1: sound good too me. I'm watching this repo closely so this is not a problem to me
