### ISSUE TITLE
Generate pages on the fly

### ISSUE THREAD

**Issue by thangngoc89** [MoOx/statinamic#169]
Here is the scenario:

I has a collection page to list all posts in my website. While everything to render this page is already there,  it would be nice if PageContainer will just render it.

I'm thinking of some kind of YAML header to disable data loading. What do you think?

**Comment by MoOx** [comment]
I think this does not really make any sense.
I mean it does in your use case, but using a markdown file with not content is weird.
This should be a page defined via the routes.js ?

Maybe we should work on a way allow url and routes defined in routes.js tobe prerendered as well? To solve #15 for example.

**Comment by thangngoc89** [comment]
That page is acctutally my homepage which is a list of posts. Do you have any idea for this yet ?

**Comment by MoOx** [comment]
Not really. For now url to prerender are "guessed" from chunks... We should add something else to read routes?

**Comment by thangngoc89** [comment]
I'm thinking about a solution for plugin to be able to manipulate url and stuff like metalsmith

**Comment by thangngoc89** [comment]
Well. After tooking a closer look at statinamic architecture,  url-to-html takes whatever inside md-collection-loader cache and generate page based on that. We can use Webpack plugin "done" event as a callback and let user mutate collection here. Sound like metalsmith right? What do you think?

**Comment by thangngoc89** [comment]
Close. In favor of #15
