### ISSUE TITLE
Add a default loading indicator between page in default boilerplate and docs

### ISSUE THREAD

**Issue by MoOx** [MoOx/statinamic#182]
Something like [topbar](http://buunguyen.github.io/topbar/)?
A simple spinner?
A content placeholder?
topbar + a content placeholder?

**Comment by thangngoc89** [comment]
I'm using a simple "Loading..." text. Since data file is small,  showing some loading indicator make you feel like some kind of lag.  Bad UX

**Comment by MoOx** [comment]
Something made with a inlined svg can be inlined in the bundle and should not make it bigger.

**Comment by thangngoc89** [comment]
A topbar sound like a good solution. But fetch api can't tell the download progress percentage.(it's in stream api). Maybe we should fake it.  Haha

**Comment by MoOx** [comment]
topbar has a nice ux. Just start() and stop() with a non linear progress that try to got to 100% until you stop.

**Comment by thangngoc89** [comment]
We will see

**Comment by thangngoc89** [comment]
A react component for topbar https://github.com/vn38minhtran/react-progress-bar-plus

**Comment by thangngoc89** [comment]
Just implemented this in [my blog](https://github.com/thangngoc89/blog/pull/60/files) 

Are you ok with adding [react-progress-bar-plus](https://github.com/vn38minhtran/react-progress-bar-plus) 

Also, I'm using recompose for a quick way to create pure component.

**Comment by thangngoc89** [comment]
Github just added the loading indicator. It's time for us to add this too. But my current approach is using redux. Any idea ?

**Comment by MoOx** [comment]
I am on it :)
