### ISSUE TITLE
"Random" 404...

### ISSUE THREAD

**Issue by MoOx** [MoOx/statinamic#183]
Catched links may be the issue.
Not even sure how to reproduce but @thangngoc89 got it too.

**Comment by thangngoc89** [comment]
Haha. Looks like you just make this more worse in https://github.com/MoOx/statinamic/commit/a707561a75bcd36852bb4ddd199e210164ca7370

Reproduce : Go to docs homepage --> ``Try it now`` button --> Checkout `configuration` 

You'll see a redirect loop here.

**Comment by MoOx** [comment]
Not that random. Fixed by #194
