### ISSUE TITLE
Back button behave weirdly when you open an internal asset

### ISSUE THREAD

**Issue by MoOx** [MoOx/statinamic#184]
Reproduce: open http://moox.io/statinamic/, got to the video, click back. Good page is not restored...

**Comment by thangngoc89** [comment]
Gonna comment it here https://github.com/MoOx/statinamic/commit/a707561a75bcd36852bb4ddd199e210164ca7370

**Comment by MoOx** [comment]
This fix is a start, but not enough.

**Comment by MoOx** [comment]
I think this will be fixed by #194

**Comment by thangngoc89** [comment]
Fixed in #194
