### ISSUE TITLE
Avoid warning of babel-plugin-webpack-loader in boilerplate

### ISSUE THREAD

**Issue by thangngoc89** [MoOx/statinamic#185]
```
babel-plugin-webpack-loader:
To avoid caching errors you need to set BABEL_DISABLE_CACHE=1 environment variable.
More information at issue #36
```

**Comment by MoOx** [comment]
We should add this in the boilerplate.

**Comment by thangngoc89** [comment]
I suggest we use [better-npm-run](https://www.npmjs.com/package/better-npm-run) for a better command. We have 2 env vars already

**Comment by MoOx** [comment]
We have cross-env already. better-npm-run will add more code.

**Comment by thangngoc89** [comment]
I mean replace cross-env with better-npm-run, it's window compat. But it's should be low priority. Just add that env to boilerplate to avoid warning

**Comment by MoOx** [comment]
What is the real benefit?

**Comment by thangngoc89** [comment]
Cleaner package.json file. No real benefit. haha
