### ISSUE TITLE
Performance issue after upgrade to 0.8.0

### ISSUE THREAD

**Issue by thangngoc89** [MoOx/statinamic#187]
I noticed that generating html static file tooks too long after upgrading to 0.8.0.

Here is some information from Travis build of statinamic master branch

0.7.1: [197ms](https://travis-ci.org/MoOx/statinamic/jobs/110829222#L2091)
0.8.0: [27s](https://travis-ci.org/MoOx/statinamic/jobs/111449156#L2147)

Maybe because of these LoC ? 

```
  const {
    layouts,
    metadata,
    routes,
  } = importExports(exports)
```

(https://github.com/MoOx/statinamic/blob/next/src%2Fstatic%2Fto-html%2Furl-as-html.js#L25-L29)

**Comment by MoOx** [comment]
Should not be the issue since when you `require()`  as same file twice, node use its cache.
No idea for now.

**Comment by thangngoc89** [comment]
I can confirm that above LoC is the problem. Revert that change and build time back to 150ms (on my laptop)

**Comment by MoOx** [comment]
You cannot just revert those lines. I introduced this to fix a lack of dev server "freshness".

**Comment by thangngoc89** [comment]
@MoOx Yes. I know. I send a PR to fix it in the first place.

**Comment by thangngoc89** [comment]
Sorry for the troubles. After doing some benchmark, there is no different at all. 

Just ``debug`` is giving false information

- 0.7.1: layouts, metadata, routes was processed in the first step, those extra seconds are counted in this step
- 0.8.0: layouts, metadata, routes was processed after webpack build so ``debug`` will show it hrer

**Comment by thangngoc89** [comment]
@MoOx what's wrong with this ?

**Comment by MoOx** [comment]
Sorry I mean #301
