### ISSUE TITLE
Dev server render error stack with redbox

### ISSUE THREAD

**Issue by thangngoc89** [MoOx/statinamic#196]
Currently, dev server only display the error log, not the full stack. We should throw the full stack on the screen.

Even better if we use [redbox](https://www.npmjs.com/package/redbox-react) to render it. 

>  you can use all the wasted space where your app would be if it didn’t crash to display the error that made it crash

**Comment by MoOx** [comment]
Redbox is used already via babel-preset-react-hmre but maybe we can do something better.

**Comment by thangngoc89** [comment]
> Redbox is used already via babel-preset-react-hmre

redbox only show up on the client.

> maybe we can do something better.

I'm listenning.

**Comment by MoOx** [comment]
No specific idea.

**Comment by thangngoc89** [comment]
So just show the error stack with redbox for now.
