### ISSUE TITLE
devServer doesn't clean markdown cache

### ISSUE THREAD

**Issue by thangngoc89** [MoOx/statinamic#198]
Related to #140 but now for markdown. Pretty annoying

**Comment by MoOx** [comment]
Can you add step to reproduce?

**Comment by thangngoc89** [comment]
Start devServer -> Edit some markdown -> Hot reloading kicks in and you'll see new content -> F5 -> You'll see old content until you edit something to retrigger hot reloading

**Comment by MoOx** [comment]
Sorry cannot reproduce on next branch.

I started dev server on docs, edited homepage, see my hot loaded change, refreshed page (rendered from dev server) and I have the correct content (with my recent modification).

Feel free to reopen with more accurate steps to reproduce.

**Comment by thangngoc89** [comment]
Can't reproduce either.
