### ISSUE TITLE
redbox does not seems to works correctly on client

### ISSUE THREAD

**Issue by MoOx** [MoOx/statinamic#202]
If you call an undefined variable for example when you switch to a new page, redbox does not handle things. I only got error in browser console.

**Comment by thangngoc89** [comment]
Work for me on syntax error 
![screenshot from 2016-02-27 01 11 06](https://cloud.githubusercontent.com/assets/3049054/13361062/1bd42500-dcef-11e5-9a71-19252c060603.png)

**Comment by MoOx** [comment]
this is not the runtime redbox (that is red, not pink). I got a case where something was undefined (this.context**e**.something) and did not get the real redbox.

**Comment by thangngoc89** [comment]
Will try to reproduce like you said

**Comment by thangngoc89** [comment]
Got it. Redbox won't show up if eslint catch the error first. Webpack failed before babel transform

**Comment by MoOx** [comment]
Cannot reproduce with my initial description.
