### ISSUE TITLE
Consume statinamic directly from Github

### ISSUE THREAD

**Issue by thangngoc89** [MoOx/statinamic#203]
For trying new feature ... without the symlink trick

**Comment by thangngoc89** [comment]
Current workaroud is using `npm install --no-bin-links`.

**Comment by MoOx** [comment]
inside node_modules/statinamic?

**Comment by thangngoc89** [comment]
Like this:

```
npm install github_link --no-bin-links
cd node_modules/statinamic && npm install && npm run babelify
```

**Comment by MoOx** [comment]
--no-bin-links make us unable to run the setup command. Will need to be documented.

**Comment by MoOx** [comment]
so this should be good

```console
$ npm install https://github.com/MoOx/statinamic.git#next --no-bin-links && cd node_modules/statinamic && npm install && npm run babelify cd ../..
```

?

**Comment by thangngoc89** [comment]
Do we need `cd ../..` ?

**Comment by MoOx** [comment]
to get back to the original cwd :)

**Comment by thangngoc89** [comment]
No need for that. cwd won't change

**Comment by MoOx** [comment]
cd node_modules/statinamic

**Comment by thangngoc89** [comment]
no. `cd node_modules/statinamic && npm run babelify`

cwd stills original folder

**Comment by MoOx** [comment]
```
~/Sync/Development/statinamic next*
❯❯ cd boilerplate && echo "lol"
lol

~/Sync/Development/statinamic/boilerplate next*
```

**Comment by thangngoc89** [comment]
Nevermind. My mistake. Sorry

**Comment by MoOx** [comment]
Maybe we can even do this in a postinstall hook if lib is not present?

**Comment by thangngoc89** [comment]
Good idea.

**Comment by thangngoc89** [comment]
Interesting https://github.com/mjackson/history/commit/4579afe77b31c1ddfadfe6d68c0992bf12756698

**Comment by thangngoc89** [comment]
We can rewrite `/src/bin/index.js` using ES5 code and bin path to this file directly. No trick needed for this to work.

**Comment by thangngoc89** [comment]
I took a different approach with small changes. But I hit a npm bug (a big bug)

https://github.com/npm/npm/issues/10686#issuecomment-178802449

Branch: https://github.com/MoOx/statinamic/tree/github-install

Sorry for the messy commits

**Comment by MoOx** [comment]
try using stdio: inherit and cwd to __dirname/.. (to be in the best place).
ALso maybe try async (no execSync npm install)

**Comment by thangngoc89** [comment]
The code must be written in ES5 so no async (maybe promise)

> cwd to __dirname/.. 

Well. cwd is already in `node_modules/statinamic/` (but I'll add that to be sure)

**Comment by MoOx** [comment]
exec(cmd, (err, stdout, stderr) => { is async :)

**Comment by MoOx** [comment]
or maybe try spawn, which will create another process

**Comment by thangngoc89** [comment]
Haha. I thought you're talking about await/async syntax.

**Comment by thangngoc89** [comment]
> or maybe try spawn

roger that.

**Comment by thangngoc89** [comment]
@MoOx so this is really a npm issue. As suggested in the original issue from npm. I tried npm@3.3.2 and it worked without an issue.

And we don't even need to run `npm run babelify`. npm will run `prepublish` hook after `postinstall`.

I rebased the branch. Should be in a better shape right now.

**Comment by MoOx** [comment]
prepublish is run locally (when you run npm install) yeah, so no need to call babelify indeed.
Is you branch working only with npm 3.3.2? Can we do something for latest npm?

**Comment by thangngoc89** [comment]
Yes. my branch is working with npm@< 3.3.2. (npm@2 too)

I'll try to spawn a new process.

**Comment by thangngoc89** [comment]
Ok. spawn a new process works.
