### ISSUE TITLE
Dev server should generate static version for url on the fly

### ISSUE THREAD

**Issue by MoOx** [MoOx/statinamic#23]
Currently we need to build a static version + run the dev server. This is counter productive. The express server should be able to generate the page on the fly directly.

**Comment by MoOx** [comment]
@thangngoc89 just to let you know that I am on this, and this will clean a LOT OF THINGS :)

**Comment by thangngoc89** [comment]
Ok.  Good to know . I means time. I'll just blogging then

**Comment by MoOx** [comment]
ETA: Almost ready :)

**Comment by thangngoc89** [comment]
Can't wait ....

**Comment by MoOx** [comment]
OMG it works. I finally fixed [the last issue I got](https://github.com/istarkov/babel-plugin-webpack-loaders/issues/13#issuecomment-180278051) (bad usage of babel-plugin-webpack-loaders).
I still have to cleanup things now and will push my work as a PR so you can review it (warning: huge pr) ^^

**Comment by thangngoc89** [comment]
Finally :)

**Comment by thangngoc89** [comment]
Awesome. About that config, webpack 2 have a better syntax to define loader with query. no more ugly JSON.stringify

**Comment by MoOx** [comment]
Yeah I see that.

**Comment by thangngoc89** [comment]
Why don't use NODE_ENV for easier babel config ?

There is 

- [cross-env](https://www.npmjs.com/package/cross-env) for windows ENV 
- [better-npm-run](https://www.npmjs.com/package/better-npm-run) for a cleaner run script in package.json

**Comment by MoOx** [comment]
Because NODE_ENV=static is used for babel-plugin-webpack-loaders and the client webpack build is run in the same process. babel-plugin-webpack-loaders does not make sense for client side code so I must disable it for client side script.

**Comment by thangngoc89** [comment]
Ah. That makes sense.
