### ISSUE TITLE
Test fail on node 4 with status code 137

### ISSUE THREAD

**Issue by thangngoc89** [MoOx/statinamic#247]
https://travis-ci.org/MoOx/statinamic/jobs/113613499#L334

---
Update:

> jamestalmage
> Try without coverage.
>
> Both nyc and ava are loading babel-core/register. In Node 4, npm does not dedupe by default, so nyc and ava may be resolving different instances of babel, so the hook may indeed be getting installed twice.
>
> If it works without coverage, then it should just be a matter of removing —require babel-core/register from your npm script.

So there is 2 solutions here : 

- Don't run coverage on node 4
- Remove `--require` and `--all` flags. (but we all know why do we add those flags in the first place)

@MoOx I wanna know your opinion about this.

**Comment by thangngoc89** [comment]
Follow up https://github.com/bcoe/nyc/issues/181

**Comment by MoOx** [comment]
Will remove --all and add empty test files that are just importing module. This will report 0% as we want to kick our own ass :D

**Comment by thangngoc89** [comment]
Ok.  I'll continue to improve test coverage
