### ISSUE TITLE
CSS bundle is not generated in build

### ISSUE THREAD

**Issue by thangngoc89** [MoOx/statinamic#253]
Ref: https://github.com/MoOx/statinamic/commit/c20b4b1f8aef1420e28c959fe3fc3029aac59efa

Disable in `BABEL_ENV=statinamic` means disable it all the time.

**Comment by MoOx** [comment]
Haha. Oups. I made this too quickly :)
I think I will start soon to add some integration tests.

**Comment by MoOx** [comment]
Haha. Oups. I made this too quickly :)
I think I will start soon to add some integration tests.

**Comment by MoOx** [comment]
I created a branch with (very) minimal integration tests: [fix/253](https://github.com/MoOx/statinamic/commit/589ecb2e4dbcfacfa77119c5aa4f0ba2a581609f).

To fix this issue properly, I think we will need to have 3 places to store webapck:

- common part
- static only (eg extractplugin always disabled)
- client only (eg extractplugin enabled if not dev)

This will allow us to avoid main generation right?
What do you think?

Maybe we should just offer people to have one config and handle the specific part under the hood? We could warn for config that will be overwritten by us so people don't have "weird use case" were their config is overwritten by us.
Not sure if we should do that. But not sure if we should not do it either :D

**Comment by MoOx** [comment]
Not that my branch run integration tests too early (because of the default ava pattern specified in package.json ava section, we should make this one better with src before the pattern).
Have to go.

**Comment by thangngoc89** [comment]
How about using https://github.com/lewie9021/webpack-configurator ?  We will expose a function to let people edit their own config?  This would help upgrading statinamic easier.

**Comment by MoOx** [comment]
This require a specific syntax for declaring your webpack configuration, so I don't like it.
So what about this:

- user config: we add a minimal configuration in boilerplate (mostly, the loaders part)
- statinamic required config: we keep a private config for static and another one for client (the "HANDLE WITH CARE" parts)
- we merge user and statinamic config BUT we throw error for all "conflicts" that will occurs with the merge AND we let people disable the error by adding a flag like "silentMerge".

Probably 90% of people will not need more things than adding some loaders and a few plugins. For the people that need some others specific option that might conflict with our, we throw an error and inform in the error the why we throw it (as well as informing how to avoid the error to be thrown, by using a flag or being more careful in what they change).

I think this will provide a good UX. Any thoughts?

**Comment by MoOx** [comment]
This will remove most of the boilerplate (that probably most people don't understand or don't want to see).

**Comment by thangngoc89** [comment]
:+1: that's a great idea. We keep everything inside statinamic, this reduce stuff that people don't understand (and don't even need to understand).

**Comment by MoOx** [comment]
On it.

**Comment by MoOx** [comment]
Closed in favor of #214 (reopened).
