### ISSUE TITLE
[next] CLI options cannot be passed with new command

### ISSUE THREAD

**Issue by MoOx** [MoOx/statinamic#262]
`statinamic start --devPort=4000` throw an error. commander try to validate all option, but we already use minimist, later in the process.
We probably need to ditch commander.

**Comment by thangngoc89** [comment]
`statinamic start -- --devPort=4000` ?

**Comment by MoOx** [comment]
No -- is a npm specitic ting. Commander try to validate all option, and I only registered --config. Will need a good cleanup between commands and API.

**Comment by thangngoc89** [comment]
[yargs](https://github.com/yargs/yargs) is a good tools for this job.

**Comment by MoOx** [comment]
We already use minimst

**Comment by thangngoc89** [comment]
How about add all available options to commander ?

**Comment by MoOx** [comment]
I will move options definition in an file so we can use in commander and in minimist too (if minimist is still relevant).

**Comment by MoOx** [comment]
Btw, I will add this https://github.com/kentcdodds/webpack-validator
