### ISSUE TITLE
Move remark and remark's plugins to optionalPeerDependencies

### ISSUE THREAD

**Issue by thangngoc89** [MoOx/statinamic#263]
#251 must be resolved first

**Comment by thangngoc89** [comment]
Or we can move default-renderer to it's own packages with it's own deps. We can have greenkeeper checking for deps sperately. And less deps in boilerplate. poke @MoOx

**Comment by MoOx** [comment]
Not a fan of this for now. 99% of users will use default engine, so until some people start to tell us to do that, it's not necessary and will add some pain to sync some changes until our API/ABI start to be stable.

**Comment by thangngoc89** [comment]
remark* are deps right now.
