### ISSUE TITLE
Remove lint check in docs

### ISSUE THREAD

**Issue by thangngoc89** [MoOx/statinamic#264]
We already have lint check in main's repo. There is no need for linting in docs. This would help speed up CI build

**Comment by thangngoc89** [comment]
poke @MoOx 

Also I often run lint inside docs instead of project root.  Haha

**Comment by MoOx** [comment]
it's to simplify copy/paste between docs and boilerplate, and it should take a second, not sure if that's a real issue.

**Comment by thangngoc89** [comment]
Ok. If it's for simplify copy/paste, i'm in

**Comment by MoOx** [comment]
Also, docs are the best example we should have, so I prefer to keep this here as it's not the responsible for the performance issue.
