### ISSUE TITLE
Upgrade to React 15.x

### ISSUE THREAD

**Issue by MoOx** [MoOx/statinamic#269]
RC is out. http://facebook.github.io/react/blog/2016/03/07/react-v15-rc1.html

**Comment by thangngoc89** [comment]
Should be painless.

**Comment by thangngoc89** [comment]
Maybe update peerDep to allow using React first. We will fix any issue later

**Comment by MoOx** [comment]
RC is not stable, anyway npm@3 just warn, so no need to bump.

**Comment by thangngoc89** [comment]
I'll setup a new branch to use React 15 RC in docs.

**Comment by thangngoc89** [comment]
Tried React 15 RC on a local branch. It's painless. It just works since we don't have any warning when using React 14

**Comment by thangngoc89** [comment]
Added via https://github.com/MoOx/statinamic/commit/1b908c9511ab9eaa070c5b07a30ab5148c36189d
