### ISSUE TITLE
Fix autodeploy from travis

### ISSUE THREAD

**Issue by MoOx** [MoOx/statinamic#27]
Doesn't work with `gh-pages-deploy-sh` (it deploy the entire repo even if you provide the right glob) or `gh-pages` (say it works from log, [but it doesn't](https://github.com/tschaub/gh-pages/issues/22))...

**Comment by MoOx** [comment]
Some alternatives:
- https://github.com/X1011/git-directory-deploy
- https://www.npmjs.com/package/buildbranch

**Comment by iamstarkov** [comment]
buildbranch is working for my blog and other projects for years

**Comment by MoOx** [comment]
I just tried buildbranch another time (that is not my first time) but it failed because of uncommited files and put my git repo in a akward state...
