### ISSUE TITLE
Disable appcache after enabled it

### ISSUE THREAD

**Issue by thangngoc89** [MoOx/statinamic#276]
Due to the way appcache work. It is impossible to disable appcache after enable it. If one remove the appcache configuration in `package.json` or switch it to falsy value. Browser will try and fail to download the `mainfest.appcache`. So the website isn't updated. I suggest we add an option to `appcache` like this:

```
"appcache: "disabled"
```

And we will write this to `manifest.appcache` : 

```
CACHE MANIFEST

NETWORK:
*
```

**Comment by MoOx** [comment]
Yeah I got the issue while I was playing in dev mode. Pretty annoying.
I was thinking about this indeed. Are you sure this "empty" file will be enough to clean all the cache?
Maybe we should use "disabled" when false? Eg: I use true, remove the value, I will expect to have no cache anymore.

**Comment by thangngoc89** [comment]
I didn't test this appcache config yet. But if I'm right, we can always write this file to dist folder to disable appcache.

**Comment by thangngoc89** [comment]
According to this SO answer : http://stackoverflow.com/a/4829472

All we need to do is not produce manifest.appcache anymore. Need to test this

**Comment by thangngoc89** [comment]
Haha. After 2 refreshes (with manifest deleted and no manifest props in <html> tags). appcache is gone.

**Comment by MoOx** [comment]
Coo.
