### ISSUE TITLE
url with anchors are being replaced with url without anchors

### ISSUE THREAD

**Issue by MoOx** [MoOx/statinamic#283]
Eg: go to http://putaindecode.io/en/articles/js/react/unit-testing/, click on a title anchor. Link works, but anchor is quickly stripped from the url bar

**Comment by thangngoc89** [comment]
It's because of these LoC https://github.com/MoOx/statinamic/blob/next/src%2FPageContainer%2Fcomponent.js#L104-L123

```
statinamic: PageContainer: replacing by '/en/articles/js/react/unit-testing/#easy-unit-testing-react-components-without-a-dom' to '/en/articles/js/react/unit-testing/'
```

**Comment by MoOx** [comment]
I know. We need to improve that to ignore anchors.

**Comment by thangngoc89** [comment]
Solution should be simple, remove `window.location.hash`
