### ISSUE TITLE
Document about required node version

### ISSUE THREAD

**Issue by thangngoc89** [MoOx/statinamic#299]
Should be node >= 4.2 (LTS)

**Comment by thangngoc89** [comment]
Can add it to package.json too

```
  "engines": {
    "node": ">=4.2.0",
    "npm": "^3.0.0"
  },
```

**Comment by MoOx** [comment]
That can probably work on node 0.12 with babel-node?
Why 4.2 ?

**Comment by thangngoc89** [comment]
We use some method that isn't compat with 0.12.
Like string.endsWith

**Comment by MoOx** [comment]
babel-polyfill might help

**Comment by thangngoc89** [comment]
Yup. But we'll need to run tests against 0.12
