### ISSUE TITLE
Change name of the project 😢

### ISSUE THREAD

**Issue by MoOx** [MoOx/statinamic#306]
EDIT:

Plans:

- [x] rename repo and all occurences in repo
- [ ] npm deprecate
- [ ] redirect doc from https://duckduckgo.com/?q=site%3Amoox.io%2Fstatinamic%2F&t=ffab to phenomic.io/*
- [x] switch twitter nick for statinamic and phenomic_app (goal: keep statinamic mention and pin a tweet to redirect people to phenomic_app account)
- [ ] add in the README and doc a mention to the old name for a moment.

---

When I started this project I was unsure about the name. And it seems I was not alone.
I received this legitimate email from [statamic](http://statamic.com/) author

> Hey Maxime, I just saw that you’ve been building a static site generator called statinamic. It looks neat. However, it’s extremely close to -- in name and purpose — my static/flat file CMS Statamic, which has been on the market since 2012. I don’t this to turn into a big thing, so I was hoping a little email might prompt you to think about renaming it. Let me just say from experience, people have a hard time saying the combination of these two words. You might even do better in the long run giving it a clever javascript-ecosystem name like “ThunderGen” or “Electro” or something. You know the drill.
>
> Thanks for you time. I wish you the best, please let me know when you get this and what you plan to do so I can plan accordingly. I much prefer to be friends with everybody!

Facts:

- statinamic has been reported to be hard to pronouce in english (however in french or Vietnamese, no problem)
- the name is too similar to a project that have a similar goal (make a website from some content).

So please share your ideas, there is no bad idea, only ideas (even the worst one will affect the final choice).

Here are some requirements:
- name is available on npm (try https://www.npmjs.com/package/THE_NAME)
- name is available on a domain that does nut suck (eg: .org, .io etc, no .beer or .website)
- name is not a generic name (I want something that have some "personality")

**Comment by zoontek** [comment]
- estatical ?
- staticable ?
- statican ?

**Comment by lionelB** [comment]
- bimbam
- sitomator

**Comment by MoOx** [comment]
-  ~~reactyll~~ (first one, but shitty)
- ~~publiship~~ (.com taken)
- shipict
- dynamict
- statictoc
- staticap
- apptic
- contactic
- staticontent
- trinitic
- trinity
- leeloo (or liloue)
- leenamic
- ofo
- unicamic
- fastux
- uxee
- statix

**Comment by vvo** [comment]
"shipict" => https://github.com/shipitjs/shipit

**Comment by vvo** [comment]
statik
statilik

**Comment by vvo** [comment]
bilibup (ok yes, I am drunk)

**Comment by Macxim** [comment]
Ecstatic
>
adjective
1. of, relating to, or characterized by ecstasy or a state of sudden, intense, overpowering emotion
2.subject to or in a state of ecstasy; full of joy; rapturous:

**Comment by MoOx** [comment]
@Macxim I would like to avoid a generic (existing) name. I would like to have something that does not exist.

Does not need to have things like "static" "atic", "ic", "react", "act", "rea" etc. We should focus the idea on the purpose of the tool: publish content with modern and composable web technologies.

**Comment by MoOx** [comment]
Some other:

- amazic
- lightnic
- explosic
- explosux
- futinamic

Not happy with one yet.

**Comment by lionelB** [comment]
- patator

**Comment by MoOx** [comment]
appinamic

**Comment by lionelB** [comment]
- happypl... #ohwait

**Comment by MoOx** [comment]
happynamic then

**Comment by thangngoc89** [comment]
happynamic.io is avaiable

**Comment by magsout** [comment]
>happynamic then


![wait-say-what-gif](https://cloud.githubusercontent.com/assets/1997108/13773439/8389e8f8-ea99-11e5-8cd1-d1615fb64ac7.gif)

**Comment by MoOx** [comment]
tactinamic

**Comment by lionelB** [comment]
titaninamic :trollface:

**Comment by MoOx** [comment]
dicaprionamic

**Comment by revolunet** [comment]
supstatic
supastatic
reactic
statimachine
staticizer
statiminer

**Comment by kewah** [comment]
* reacstic
* dynastic
* dealwithstic :trollface:

**Comment by TrySound** [comment]
По-русски статинамик тоже норм. Who cares english? :)

**Comment by MoOx** [comment]
@TrySound hahaha.

**Comment by Nickdouille** [comment]
My 2 cents !

Brickable
Brickomatic
Publicomatic

**Comment by MoOx** [comment]
Phenomic
Phenomenic

**Comment by MoOx** [comment]
McFlip

**Comment by Macxim** [comment]
> Phenomic
:+1: :100: 

Plus it kind of relates to :
> Phenomics is an area of biology concerned with the measurement of phenomes — the physical and biochemical traits of organisms — as they change in response to genetic mutation and environmental influences.

**Comment by MoOx** [comment]
Fastinamic

**Comment by MoOx** [comment]
Fastflip

**Comment by zoontek** [comment]
Chocolatinic

**Comment by MoOx** [comment]
Stuntinamic

**Comment by MoOx** [comment]
Crazynamic

**Comment by thangngoc89** [comment]
> Crazynamic

This one is good

**Comment by TrySound** [comment]
Statimaniac.

**Comment by MoOx** [comment]
@TrySound nice !

**Comment by MoOx** [comment]
Stateenamic

**Comment by rafaelrinaldi** [comment]
dynast (**Dyna**mic **St**atic)
stadyn (**St**atic **Dyn**amic)

**Comment by magsout** [comment]
@TrySound 👍

**Comment by thangngoc89** [comment]
@TrySound dose it have any meaning :D

**Comment by MoOx** [comment]
Smoothic

**Comment by kewah** [comment]
mooxic

**Comment by TrySound** [comment]
@thangngoc89 Does not look like statamic in any case.

**Comment by MoOx** [comment]
staminamic

**Comment by MoOx** [comment]
staminatic

**Comment by TrySound** [comment]
StaticExtraordinaric

**Comment by lionelB** [comment]
A java falvor one 
`StaticSiteServiceGeneratorReactStrategyClass`

**Comment by MoOx** [comment]
Maybe we can stick to serious proposals :)

**Comment by lionelB** [comment]
What do you plan about the name choice ?
 - community chosen one, so to move on, we should decide when close the name submission and then do a 2nd turn, selecting only the 3 best proposition and make a short list.
-  would you like to have the final word on the name 
- would you like to make a short list and let we discuss it ?

**Comment by MoOx** [comment]
There is no community at the moment, only 2/3 open source projects use this and current users barely voted atm. So I will leave this open for now.

My idea is to select 4 names (deadline: before v1), and make a twitter poll.

**Comment by forresst** [comment]
dyna**mic** and sta**tic** : mictic

With a [good definition](http://encyclopedia2.thefreedictionary.com/mictic) and [simple logo](http://www.intechopen.com/source/html/48540/media/image2.png) !

(ok I go out)

**Comment by MoOx** [comment]
fantastinamic

**Comment by MoOx** [comment]
cosminamic

**Comment by MoOx** [comment]
fantasmic

**Comment by marcustisater** [comment]
Are we still sticking with the `mic'ish` suffix? So far I like the [suggestion](https://github.com/MoOx/statinamic/issues/306#issuecomment-196882450) from @maxcim 

> Phenomic

**Comment by thangngoc89** [comment]
@marcustisater @MoOx required that it must be an adjective

**Comment by MoOx** [comment]
Not stuck with anything.

PS: [I think that's my idea ^^](https://github.com/MoOx/statinamic/issues/306#issuecomment-196880438)

I start to like this one.

@thangngoc89 it's not required to be an adjective. I just wanted to have something original :)

**Comment by marcustisater** [comment]
Whoops sorry, must have skipped through...

Twitter poll! :+1:

**Comment by MoOx** [comment]
Soon ;)

**Comment by MoOx** [comment]
From what we can see, with the github reactions, the poll will be made with those 4:

- Happynamic
- Phenomic
- Crazynamic
- Statimaniac

I skipped "mictic" since imo it's too close to meetic (and weird to pronounce).

If I should pick one right now, I will go for **Phenomic** because it's simple, not a lot of syllable.

Statimaniac and Crazynamic sounds not serious enough to me, and Happynamic is too long imo.

Do you think that a twitter poll is necessary guys?

If you think so, I might reserve myself the right to have the final word if results are not very clear (eg: too few voters or results too close (eg: one to 34% and the other to 32%) since I spent a loooots of time on this project (according to my calendar, around 300 hours so approximatively)

**Comment by marcustisater** [comment]
You should feel comfortable with the name and you have every right to decide the final call, we were just helping you with **suggestions**. 

> Phenomic

btw, good choice :wink:

**Comment by thangngoc89** [comment]
> Phenomic 

good name

**Comment by lionelB** [comment]
> I might reserve myself the right to have the final word if results are not very clear

it's your project... no pb with that.
I've not any prefered choice from the shortlist (not so fan of  -mic thing) 
I would choose
> Statimaniac

**Comment by MoOx** [comment]
Poll ! https://twitter.com/statinamic/status/711973125366403072

**Comment by MoOx** [comment]
Poll current status

11%Happynamic
51%Phenomic
23%Statimaniac
15%Crazynamic

35 votes • 6 hours left.

**Comment by MoOx** [comment]
If there is no objections, I will probably start the renaming next weeks.

This will involves:
- npm deprecate
- a single unix command to replace statinamic with the new name in your entire project
- a domain name ?
- redirection for the doc

**Comment by MoOx** [comment]
FYI http://phenomic.io/ and https://www.npmjs.com/package/phenomic are things :)

**Comment by thangngoc89** [comment]
What do you think about a Github orgs ?

**Comment by MoOx** [comment]
> What do you think about a Github orgs ?

Not ready for this yet, probably someday :)

For Twitter handle, `@phenomic` is already taken but not really used so I tweeted to the user, but no response yet. So I took `Phenomic_app`. Any better idea for the handle in case we have to choose something else than `phenomic`?

**Comment by marcustisater** [comment]
Pheomic_app is great :+1:

**Comment by gristel** [comment]
@dynastic - Dynastic_app :-D

**Comment by MoOx** [comment]
So about the website, I would like to setup https, since it's now supposed to be easy thanks to Let's Encrypt.

Solutions:
- use cloudflare in front of github pages
- use kloudsec in front of github pages https://kloudsec.com/github-pages/new
- use gitlab pages that provide https for gitlab pages (but keep github as the repo for issues/pr etc)

I would like to try gitlab pages, that might help for #366.
I am currently trying a new trend: have my repo on multiple git services (github+gitlab+bitbucket). It's very easy. You can push and pull without any problem.
You can see example of this https://github.com/MoOx/eslint-config-i-am-meticulous (checkout badges, so repo & tags).

Thoughts?

**Comment by thangngoc89** [comment]
I prefer Cloudflare. It has a super fast DNS change. Also others useful stuff like http2,  ddnssec,  ...

**Comment by MoOx** [comment]
Cloudflare has been setup. https://phenomic.io works and redirect to statinamic current doc until we cut the release.
I already switched twitter.com/Phenomic_app with twitter.com/Statinamic.
TODO list on #387.
