### ISSUE TITLE
run coverage task only fr merge build

### ISSUE THREAD

**Issue by MoOx** [MoOx/statinamic#315]
I think we have weird result because travis create 2 reports, one for branch and one for pr. Maybe pr is enough?

**Comment by thangngoc89** [comment]
Yes. It's pretty annoying when sending a PR and `push` build provide a fake (usually higher than the `pr` build`).

Example 

- [PR build](https://codecov.io/github/MoOx/statinamic?ref=913c00fc97b0835763d154fdf13e1ffb1e3121ca)
- [Push build](https://codecov.io/github/MoOx/statinamic?ref=8324384769239578e59105ecd55e3e1ba65a9f63)

But I think more important is why is there a difference between pr and push. Is nyc drunk ?
