### ISSUE TITLE
use portfinder to avoid error when port is used

### ISSUE THREAD

**Issue by MoOx** [MoOx/statinamic#320]
https://github.com/indexzero/node-portfinder

**Comment by thangngoc89** [comment]
I can handle this. I use port-finder for most of ny project

**Comment by MoOx** [comment]
Please wait for #262 to be resolved.

**Comment by MoOx** [comment]
What about this smaller package that use a promise https://github.com/sindresorhus/get-port ?

**Comment by thangngoc89** [comment]
It's not correct.

See http://stackoverflow.com/questions/9901043/how-does-node-js-choose-random-ports
and https://gist.github.com/mikeal/1840641

Also, we don't need get-port to use that method.
