### ISSUE TITLE
.gitignore is renamed to .npmignore in boilerplate

### ISSUE THREAD

**Issue by thangngoc89** [MoOx/statinamic#323]
This issue from npm was there since 2011 (https://github.com/npm/npm/issues/1862)

For those who wanna contribute to statinamic. This is a easy patch. Just rename .npmignore to .gitignore after boilerplate is copied

Ref: https://github.com/MoOx/statinamic/blob/81baba84c5b8a49564ef8b2c82996148bf8f02ed/src/bin/commands/setup.js#L51-L52

**Comment by thangngoc89** [comment]
I'll do it. It's annoying

**Comment by MoOx** [comment]
why are this thing converted in the first place ?!

**Comment by thangngoc89** [comment]
It is converted during npm publishing progress.

**Comment by MoOx** [comment]
so maybe we can convert back in the npm postinstall hook. So if someone open the boilerplate in node_modules, it don't have inconsistency.

**Comment by thangngoc89** [comment]
@MoOx good idea. Will do it instead.
