### ISSUE TITLE
[next] context-loader bugs

### ISSUE THREAD

**Issue by thangngoc89** [MoOx/statinamic#325]
There is 2 bugs with latest content-loader: 

- Default loader should not be required [at the top of the file](https://github.com/MoOx/statinamic/blob/81baba84c5b8a49564ef8b2c82996148bf8f02ed/src/content-loader/index.js#L12). This would require user install remark-* while they don't need them. 

- webpack's loader parser remove all function from query ==> no custom engine

I suggest we ditch webpack loader's query completely and use a custom field in webpack config

**Comment by MoOx** [comment]
- we will use require() for this
- https://github.com/webpack/core/issues/13

**Comment by thangngoc89** [comment]
Ok. But not a good solution imho. This requires an extra file just for rendering markdown (or whatever).

**Comment by MoOx** [comment]
import === require, we should just call the require if no custom rendered passed.

**Comment by thangngoc89** [comment]
I mean an extra file in user's project.

**Comment by MoOx** [comment]
No need for an extra file. We can just remove `import defaultRenderer from "./default-renderer"import defaultRenderer from "./default-renderer"` and use `const renderer = query.renderer || require("./default-renderer")`.

**Comment by thangngoc89** [comment]
And what about custom renderer ? user puts result of `require.resolve` to it ? Or we move the loader config to webpack config ? (like postcss-loader)
