### ISSUE TITLE
boilerplate: PageError layout is complaining about propTypes

### ISSUE THREAD

**Issue by thangngoc89** [MoOx/statinamic#357]
See docs PageError layout for example implementation

```
Warning: Failed propType: Required prop `error` was not specified in `PageError`. Check the render method of `PageContainer`.
Warning: Failed propType: Required prop `errorText` was not specified in `PageError`. Check the render method of `PageContainer`.
```

**Comment by MoOx** [comment]
How do you access the page error? real 404? dev 404? 404.html?

**Comment by thangngoc89** [comment]
I don't access it. It shows up in the terminal when I run `statinamic start`

**Comment by MoOx** [comment]
from docs? boilerplate? your project?

**Comment by thangngoc89** [comment]
I said shit. Nevermind. You can install a fresh boilerplate. Go to `/404.html` route and you'll see the error.

**Comment by thangngoc89** [comment]
This is the extract commit to fix this https://github.com/thangngoc89/dnh-blog/commit/0cea272206a68bde86f2afb85a233033e327ae15

**Comment by MoOx** [comment]
It's not logical to provide an 404 as a default value for an error page. I did that in the past but reverted (can't remember why). Will try an alternative solution.
