### ISSUE TITLE
Change way to add global styles

### ISSUE THREAD

**Issue by kuzvac** [MoOx/statinamic#362]
I found this interesting situation, that if i add global styles with @import (for example import normalize.css, or google fonts) through LayoutContainer style file (as it is done in boilerplate), it doesn't work. Get an error:

>  site/node_modules/statinamic/lib/static/index.js:13
>       throw error;
>       ^
> 
> TypeError: Cannot read property 'layout' of undefined
>     at Layout.render (index.js:25:24)
>     at [object Object].ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext (site/node_modules/react/lib/ReactCompositeComponent.js:678:34)
>     at [object Object].ReactCompositeComponentMixin._renderValidatedComponent (site/node_modules/react/lib/ReactCompositeComponent.js:698:32)
>     at [object Object].ReactCompositeComponentMixin.performInitialMount (site/node_modules/react/lib/ReactCompositeComponent.js:283:30)
>     at [object Object].ReactCompositeComponentMixin.mountComponent (site/node_modules/react/lib/ReactCompositeComponent.js:236:21)
>     at Object.ReactReconciler.mountComponent (site/node_modules/react/lib/ReactReconciler.js:39:35)
>     at [object Object].ReactCompositeComponentMixin.performInitialMount (site/node_modules/react/lib/ReactCompositeComponent.js:289:34)
>     at [object Object].ReactCompositeComponentMixin.mountComponent (site/node_modules/react/lib/ReactCompositeComponent.js:236:21)
>     at Object.ReactReconciler.mountComponent (site/node_modules/react/lib/ReactReconciler.js:39:35)
>     at [object Object].ReactCompositeComponentMixin.performInitialMount (site/node_modules/react/lib/ReactCompositeComponent.js:289:34) 

But if i add this global styles file through scripts/index-client.js it work properly.
I spent a few hours on this shit, thinking why it does not work :D

**Comment by thangngoc89** [comment]
I think the error is obvious. You removed the declaration of styles but you didn't remove it usage.

See 

https://github.com/MoOx/statinamic/blob/eb4e94ff4d4843a258a8f2fbda7087c173b66c28/boilerplate/web_modules/LayoutContainer/index.js#L25

And https://github.com/MoOx/statinamic/blob/eb4e94ff4d4843a258a8f2fbda7087c173b66c28/boilerplate/web_modules/LayoutContainer/index.js#L33

**Comment by kuzvac** [comment]
Heh, yes. My fault :)
