### ISSUE TITLE
Short css class names on production build 

### ISSUE THREAD

**Issue by thangngoc89** [MoOx/statinamic#371]
Right now, class names is very long and take spaces in HTML, CSS, and JS too.

For example : 

`web_modules-LayoutContainer-index--content--sKdOR`

It's very long and mostly useless. no body need to know about that. 

I setup a few of my website to use a shorter class names on production build. 

It contains only 5 characters based on base64 hash. See https://github.com/thangngoc89/statinamic-theme-lumen/blob/1112ba4bc581b60b25b1aacad784285cc790172e/scripts/webpack.config.babel.js#L43-L54

What do you think about this optimization ? Should I add it to the boilerplate?

**Comment by kuzvac** [comment]
Ho. I think it's good idea. "Full path" good for dev build, we can understand what module used this style. 
For production we can use shorter class name.

**Comment by MoOx** [comment]
It was like that in older versions, I think I dropped with without paying attention during a refactoring. Will add it back.
