### ISSUE TITLE
Allow custom url (eg: 404.html)

### ISSUE THREAD

**Issue by MoOx** [MoOx/statinamic#47]
Currently you cannot choose your url that are "guess" from your md files (`content/whatever.md` => `/whatever/`).
On GitHub pages, 404.html is used as a default page when an http 404 issue is raised. We need a solution to handle this case.
Simple solution is to support an `url` field in the md metadata header. Not sure if that's a good idea, but that will do the job and is flexible enough for other use-cases.

**Comment by MoOx** [comment]
url? permalink? route? Which name is better? Jekyll & Wordpress use permalink. Not sure why they don't simply use `url`.

**Comment by MoOx** [comment]
According to the wikipedia definition of Permalink https://en.wikipedia.org/wiki/Permalink a simple field that might change is not a permalink, so I guess `url` or `uri` (since we don't have to enter the full url) make more sense.

**Comment by magsout** [comment]
`routeˋ sounds good for me

**Comment by MoOx** [comment]
I will go with route (make sense since we already use routes somewhere). On it.

**Comment by MoOx** [comment]
On it. I think I have an idea to handle this pretty quickly in an elegant manner.

**Comment by piruetka** [comment]
:+1:

**Comment by MoOx** [comment]
I have a local wip that works like a charm. Will push this evening or tomorrow if everything is ok.

**Comment by MoOx** [comment]
Closed by  865622e
