### ISSUE TITLE
Build broken on appveyor/npm@3

### ISSUE THREAD

**Issue by MoOx** [MoOx/statinamic#62]
https://ci.appveyor.com/project/MoOx/statinamic/build/41/job/xeld5cy5m6ek0r58#L1769

```
npm WARN ENOENT ENOENT: no such file or directory, open 'C:\projects\statinamic\docs\node_modules\README.md\package.json'
```

This is weird :/

**Comment by MoOx** [comment]
Ok lint is good now. Let's fix real errors.

https://ci.appveyor.com/project/MoOx/statinamic/build/200/job/p2l5a18tp5ybwr4v#L643

**Comment by thangngoc89** [comment]
There is `path.sep` method for this.  Just replace basename in that test with it

https://nodejs.org/api/path.html#path_path_sep

**Comment by MoOx** [comment]
Windows is ok now.
