### ISSUE TITLE
Setup script prematurely logs "Required dependencies successfully installed."

### ISSUE THREAD

**Issue by mxstbr** [MoOx/statinamic#65]
After seeing "Required dependencies successfully installed." in the console, I assumed it was done and `CTRL + C`'d it because the process didn't exit. Turns out, not all peerDeps were installed.

**Comment by MoOx** [comment]
Can you tell me what version of npm and are you using?

**Comment by mxstbr** [comment]
node v5.0.0
npm v3.3.9

**Comment by MoOx** [comment]
Ok thx will take a look, i have to enhance this command anyway.
