### ISSUE TITLE
Non-transpiled boilerplate?

### ISSUE THREAD

**Issue by mxstbr** [MoOx/statinamic#66]
Does the non-transpiled boilerplate with JSX and so on exist?

**Comment by MoOx** [comment]
OMG I didn't think about that. I guess the one you mention is in the npm package un lib/boilerplate ?
I need to improve the way you get it.
Anyway for now you should grab it from src/boilerplate (not sure it's in the npm package, but you can found it in this repo).

**Comment by mxstbr** [comment]
:+1: it feels weird to work with the transpiled one.

**Comment by mxstbr** [comment]
:+1: thanks, great job!!

**Comment by MoOx** [comment]
Btw, basic setup should be very easy now http://moox.io/statinamic/docs/setup/
