### ISSUE TITLE
Highlight code correctly in doc

### ISSUE THREAD

**Issue by MoOx** [MoOx/statinamic#69]
For now it's pretty shitty.

**Comment by mxstbr** [comment]
Have done dynamic client-side code highlighting with prism.js for http://sharingbuttons.io, can take a look if you want me to. 

A solution that adds the highlighting on build would probably be nicer though...

**Comment by MoOx** [comment]
Currently the code is processed during the "markdown to html" conversion so it's prerendered.
I am using highlight.js but with a stupid custom theme. Maybe just doing CSS will fix the thing. I will see.

**Comment by thangngoc89** [comment]
An example https://github.com/thangngoc89/blog/blob/1c16d9063c5f86b3f54e2ffeaa39e3b39157b4bd/web_modules/styles/vendors/_hljs.scss

You can get different theme from 
https://highlightjs.org/static/demo/

(just view source code for css)

**Comment by MoOx** [comment]
Thanks, will check this and update doc too :)

**Comment by thangngoc89** [comment]
I filed an PR on #110

**Comment by MoOx** [comment]
Closed by 23a781ef24ccd44dd291d7d2e6f1ee874bdf1ceb
