### ISSUE TITLE
Default package.json as download

### ISSUE THREAD

**Issue by mxstbr** [MoOx/statinamic#74]
Have the default package.json as a download able file from the docs, would be a nice addition.

Maybe with a form that automatically fills in your name and website?

**Comment by MoOx** [comment]
That's a good idea that I though about yesterday.
But the fact that the setup need to be done this way maybe mean that's not really accessible.
Maybe we should instead reverse the process:

```console
$ mkdir site && cd site
$ npm install statinamic
$ ./node_modules/.bin/statinamic setup
# this should create/update a package.json with statinamic version in devdeps
# + download deps
# + ask required/optional fields/value (eg: google analytics/disqus id...) and add them?
```

**Comment by mxstbr** [comment]
:+1: sgtm

**Comment by thangngoc89** [comment]
As statinamic has a lots of deps. For 0.6.1, it takes 3 mins to run `npm install statinamic` on my laptop. I think it would be better to create a seperate `statinamic-cli`. The install process of statinamic will be like this:

```
$ npm install -g statinamic-cli
$ statinamic init my-awesome-website
# Ask for informations
# Download lastest tarball from github
# Copy boilerplate to my-awesome-website folder
# Generate package.json based on given informations
$ cd my-awesome-website && npm install
```

**Comment by MoOx** [comment]
-g is not an option imo.
But we will need to improve that.
Anyway you have to install statinamic, before or after some "init" commands, that changes nothing.

**Comment by thangngoc89** [comment]
We can close this

**Comment by MoOx** [comment]
:+1:
