### ISSUE TITLE
Responsive docs

### ISSUE THREAD

**Issue by mxstbr** [MoOx/statinamic#75]
Make documentation responsive so I can read it on the go.

If you want me to I could take a look at doing this!

**Comment by MoOx** [comment]
Good idea. I did the current "theme" pretty quickly.  Should be easy to add minimal styles so it's confortable on a small screen.

- padding on body
- smaller font-size (1rem?)
- add padding to nav item + flex wrap

**Comment by MoOx** [comment]
I pushed some updates (travis will auto deploy in a few minutes...).
Reopen is that's not enough :)
