### ISSUE TITLE
How to use a custom page layout

### ISSUE THREAD

**Issue by mxstbr** [MoOx/statinamic#77]
[This part of the documentation](http://moox.io/statinamic/docs/usage/layouts/) mentions how to **add** new page layouts, but I still have no idea how to **use** it when I've added it to the `web_modules` folder and to the `app/pagesComponent.js` file.

How can I specify which layout to use when adding a Markdown file to the `content` folder?

**Comment by MoOx** [comment]
in yaml header: `layout: ComponentName # defined in app/pagesComponent.js`. This is mentionned here  http://moox.io/statinamic/docs/usage/write/#header
I will enhance this part of the doc as it's not clear :)
