### ISSUE TITLE
Add something to easily generate a meta description from page content

### ISSUE THREAD

**Issue by mxstbr** [MoOx/statinamic#79]
Talking about these LoC in the boilerplate: https://github.com/MoOx/statinamic/blob/3ba0b9ffd691f48b6554359bd6f73f04d70af684/boilerplate/web_modules/Page/index.js#L6-L8

What is the use of having that function?

**Comment by MoOx** [comment]
That was a reminder to found a solution to generate meta description tag based on the content of the page https://github.com/MoOx/statinamic/blob/3ba0b9ffd691f48b6554359bd6f73f04d70af684/boilerplate/web_modules/Page/index.js#L45
In short: markdown > html > strip html > get X first words.
Renaming this issue to handle that someday :)

**Comment by thangngoc89** [comment]
For algorithm, this is a good example https://github.com/simbo/metalsmith-better-excerpts

**Comment by thangngoc89** [comment]
I'm working on this. Should I throw this into description field in collection ?

**Comment by MoOx** [comment]
Why not :)

**Comment by MoOx** [comment]
Closed by 47dddd754d91177172701287e81d7bcf157ae9df
