### ISSUE TITLE
web_modules folder structure update

### ISSUE THREAD

**Issue by mxstbr** [MoOx/statinamic#81]
See https://github.com/postcss/postcss.com/issues/13#issuecomment-170243565

**Comment by MoOx** [comment]
Make sense. Will handle that at the same time as #80.

**Comment by MoOx** [comment]
Reminder:
- web_modules/* => low level components
- web_modules/layouts/* => page level components ("layouts" will depend on #80)

**Comment by MoOx** [comment]
Also https://github.com/postcss/postcss.com/pull/45#issuecomment-170269926

**Comment by mxstbr** [comment]
I (more or less) copy and pasted my changes from [postcss/postcss.com](https://github.com/postcss/postcss.com) and submitted a PR with these updates, see #85
