### ISSUE TITLE
Rename "routes" to "RouteHandler"?

### ISSUE THREAD

**Issue by mxstbr** [MoOx/statinamic#82]
You can't really configure your routes in `routes.js`, so we should rename the file and the variable to `RouteHandler`, which makes more sense imo.

(Also change the variable the client expects in the `index-client.js` and the `index-static.js` files to "RouteHandler")

**Comment by MoOx** [comment]
Why can't you? You can totally add new routes, like your own app to be fair... Unless I missed something else?

**Comment by mxstbr** [comment]
Yes that's true, but you don't have to add new routes to get the content.

I.e. if you have an `about.md` file in the `content/` folder, you **don't** have to go to `routes.js` and add an `<Route path="about" />`. I initially thought that was the case and it confused me for a while.

**Comment by MoOx** [comment]
So maybe that's a documentation issue?

**Comment by mxstbr** [comment]
I think it's a naming issue, calling the component "RouteHandler" makes more sense and tells users they don't need to edit it. I don't think documentation should be added if better naming would help solve the problems.

**Comment by MoOx** [comment]
I will double check "react-router" terminology before doing this change.
But if you are confused, it's clear that something need to be changed/adjusted.

**Comment by MoOx** [comment]
RouteHandler term has been deprecated since react-router v1, so I will pass. Thanks anyway @mxstbr.
