### ISSUE TITLE
Rename pageComponents to layouts

### ISSUE THREAD

**Issue by mxstbr** [MoOx/statinamic#83]
When you create the Statinamic Redux store (in `store.js`), you pass a variable called `pageComponents` which is an object containing all layout options.

This should be called `layoutComponents` or, in my opinion even better because shorter, `layouts`. Immediately clear what that variable contains, whereas the link between the `layout` variable in the YAML Front Matter of the content files and the `pageComponents` variable is very wonky and makes it hard to understand what's going on.

**Comment by MoOx** [comment]
That's a very good idea.
I think this need to be handled with the "layout" naming change.
Thanks for raising this.

**Comment by MoOx** [comment]
Closed by 650584bb1ce972a6e2944e87330fc2d5e11867ad
