### ISSUE TITLE
Generated links are not good fir the static version

### ISSUE THREAD

**Issue by cedricdelpoux** [MoOx/statinamic#9]
Generated links are not good for the static version

If I try in your demo to go to other pages, I go to `file:///routeName`

**Comment by MoOx** [comment]
How do you check those link ? If you are opening raw html from your filesystem, it's a "normal" behavior.
Links will work only from a "server" (not file:// protocol).

**Comment by cedricdelpoux** [comment]
Yes I opened directly from my filesystem. Sorry my bad :)
