### ISSUE TITLE
collection pages are not correctly prerendered (or the opposite)

### ISSUE THREAD

**Issue by MoOx** [MoOx/statinamic#96]
Ref https://github.com/MoOx/statinamic/issues/92

**Comment by MoOx** [comment]
Ref https://github.com/MoOx/statinamic/issues/92

**Comment by thangngoc89** [comment]
In my case, that is the opposite

**Comment by thangngoc89** [comment]
@MoOx is this ok now?

**Comment by MoOx** [comment]
Will double check on a big project when upgrade will be done. But I hope this will be good :)

**Comment by thangngoc89** [comment]
I hope so.  I dont have time to upgrade my blog atm

**Comment by thangngoc89** [comment]
I confirm that this issue was fixed in 0.7.0

**Comment by MoOx** [comment]
Cool.
