### ISSUE TITLE
Keep "layouts" reference in React context, not in Redux store

### ISSUE THREAD

**Issue by thangngoc89** [MoOx/statinamic#97]
because functions can't be serialized to JSON. This breaks persistState in devTools

**Comment by MoOx** [comment]
Any exact pointers on what is causing an issue for you?

**Comment by thangngoc89** [comment]
I'm testing on #91 

First, save it: http://localhost:3000/?debug_session=foo
Open new tab, go to that address

`pageComponents={}` 

Basicaly, persistState dump the current state to localStorage. Since functions can't be serialized to JSON, It would break persisState functionality

**Comment by MoOx** [comment]
Oh I see. Yeah I think we should use react context for this. Don't you think?

**Comment by thangngoc89** [comment]
Yup. Please read my comment at #40

**Comment by MoOx** [comment]
So will move "layouts" (I just renamed "pageComponents" as "layouts" in master) out of the store, and will use context for this.

**Comment by thangngoc89** [comment]
:+1:

**Comment by MoOx** [comment]
That's already good in master https://github.com/MoOx/statinamic/blob/813aafc3b32608a7281270610905f4000e95f133/src/ContextProvider/index.js
