### ISSUE TITLE
Move some opinionated peerDependencies as optionalDeps (or somewhere else)

### ISSUE THREAD

**Issue by thangngoc89** [MoOx/statinamic#99]
IMHO, I would remove these packages as peerDependencies. They are too opinionated

```
"eslint-config-i-am-meticulous": "^2.0.0",
```

Maybe others eslint packages as well. User can add there own preset of eslint or using a different linting options

The same reason for stylelint

```
"stylelint": "^4.0.0",
"stylelint-config-standard": "^1.0.0",
```

What if I want to use SASS instead of cssnext ?

```
"postcss-browser-reporter": "^0.4.0",
"postcss-cssnext": "^2.4.0",
"postcss-loader": "^0.7.0",
"postcss-reporter": "^1.3.0",
```

**Comment by MoOx** [comment]
Maybe opininated (optional) deps should be in referenced in optionalDependencies.
For peer deps are deps used by the default boilerplate (and I think default boilerplate should be a rock solid standard).

For eslint, I should indeed maybe just offer something more "standard" (eslint-config-standard or eslint:recommended).

For stylelint and postcss, like I said in the beginning of my comment, it should be optional but still referenced somewhere so the default boilerplate "just works" by default.

**Comment by thangngoc89** [comment]
> Maybe opininated (optional) deps should be in referenced in optionalDependencies.

Yes. Then merge them into devlDependencies on initial setup right ?

**Comment by MoOx** [comment]
Currently (with latest npm version) peerDeps are not installed, so I am using a trick in the "setup" script to read and install them (saved as dev deps). So we could just save them as dev deps, and if people remove deps, it won't produce any warning. Sound like a solution?

**Comment by thangngoc89** [comment]
Are you sure? When I remove those deps from devDeps, npm produces warnings about `UNMET-DEPENDENCIES` , this breaks my build (npm@3)

**Comment by MoOx** [comment]
Because it's in your dev deps AND in statinamic peerdeps. My proposal is to remove from statinamic peer deps (and move to optional) in order to avoid the warning.

**Comment by thangngoc89** [comment]
:+1:  sound like a solution

**Comment by MoOx** [comment]
So

- we should move this (eslint, eslint config, stylelint stylelint config, postcss-* and maybe some other optional peer deps) under a "optionalPeerDependencies" section
- we should install those in the "setup" script (since default boilerplate need those)
